
Geozet={};Geozet.Format={};Geozet.Format.XLSLUS={};Geozet.Format.XLSLUS=OpenLayers.Class(OpenLayers.Format.XML,{defaultVersion:"1.1.0",version:"1",parser:Geozet.Format.XLSLUS.v1,initialize:function(options){OpenLayers.Format.XML.prototype.initialize.apply(this,[options]);},writeGeocodeRequest:function(address,options){var version=(options&&options.version)||this.version||this.defaultVersion;if(!this.parser||this.parser.VERSION!=version){var format=Geozet.Format.XLSLUS["v"+version.replace(/\./g,"_")];if(!format){throw"Can't find a XLSLUS parser for version "+
version;}
this.parser=new format(options);}
var root=this.parser.writeGeocodeRequest(address);return OpenLayers.Format.XML.prototype.write.apply(this,[root]);},writeReverseGeocodeRequest:function(position,options){var version=(options&&options.version)||this.version||this.defaultVersion;if(!this.parser||this.parser.VERSION!=version){var format=Geozet.Format.XLSLUS["v"+version.replace(/\./g,"_")];if(!format){throw"Can't find a XLSLUS parser for version "+
version;}
this.parser=new format(options);}
var root=this.parser.writeReverseGeocodeRequest(position);return OpenLayers.Format.XML.prototype.write.apply(this,[root]);},read:function(data,options){if(typeof data=="string"){data=OpenLayers.Format.XML.prototype.read.apply(this,[data]);}
var root=data.documentElement;var version=this.version;if(!version){version=root.getAttribute("version");if(!version){version=this.defaultVersion;}}
if(!this.parser||this.parser.VERSION!=version){var format=Geozet.Format.XLSLUS["v"+version.replace(/\./g,"_")];if(!format){throw"Can't find a XLSLUS parser for version "+
version;}
this.parser=new format(options);}
var xlslus=this.parser.read(data);return xlslus;}});Geozet.Format.XLSAddress=OpenLayers.Class({addressee:null,countryCode:null,freeFormAddress:null,street:null,building:null,place:null,postalCode:null,initialize:function(countryCode,options){this.street=[];this.place={CountrySubdivision:null,CountrySecondarySubdivision:null,Municipality:null,MunicipalitySubdivision:null};OpenLayers.Util.extend(this,options);this.countryCode=countryCode;},format:function(){if(this.freeFormAddress){return this.freeFormAddress;}else{return this.getStreetText()+' '+this.getBuildingText()
+' '+this.getPostalCodeText()+' '+this.getPlaceText();}},getStreetText:function(address){if(!address){address=this;}
var text='';for(var si=0;si<address.street.length;si++){if(text!=''){text+=' ';}
text+=address.formatObject(address.street[si],Geozet.Format.XLSAddress.formattedStreetProperties);}
return text;},getBuildingText:function(address){if(!address){address=this;}
return address.formatObject(address.building,Geozet.Format.XLSAddress.formattedBuildingProperties);},getPostalCodeText:function(address){if(!address){address=this;}
return!address.postalCode?'':address.postalCode;},getPlaceText:function(address){if(!address){address=this;}
return address.formatObject(address.place,Geozet.Format.XLSAddress.formattedPlaceProperties);},formatObject:function(obj,props){if(!obj){return''};var text='';if(typeof obj=='string'){text=obj;}else if(props instanceof Array){for(var pi=0;pi<props.length;pi++){if(obj[props[pi]]){if(text!=''){text+=' ';}
text+=obj[props[pi]];}}}
return text;},CLASS_NAME:"Geozet.Format.XLSAddress"});Geozet.Format.XLSAddress.formattedPlaceProperties=['Municipality','MunicipalitySubdivision','CountrySecondarySubdivision','CountrySubdivision'];Geozet.Format.XLSAddress.formattedStreetProperties=['directionalPrefix','typePrefix','officialName','typeSuffix','directionalSuffix','muniOctant'];Geozet.Format.XLSAddress.formattedBuildingProperties=['number','subdivision','buildingName'];Geozet.Format.XLSLUS.v1=OpenLayers.Class(OpenLayers.Format.GML,{namespaces:{xls:"http://www.opengis.net/xls",gml:"http://www.opengis.net/gml",xsi:"http://www.w3.org/2001/XMLSchema-instance"},defaultPrefix:"xls",schemaLocation:null,addressClass:Geozet.Format.XLSAddress,srsName:'EPSG:28992',initialize:function(options){OpenLayers.Format.GML.prototype.initialize.apply(this,[options]);},read:function(data){var xlslus=[];this.readChildNodes(data,xlslus);return xlslus;},readers:{"xls":{"GeocodeResponse":function(node,xlslus){this.readChildNodes(node,xlslus);},"GeocodeResponseList":function(node,xlslus){var responseList={};responseList.features=[];responseList.numberOfGeocodedAddresses=node.getAttribute("numberOfGeocodedAddresses");this.readChildNodes(node,responseList);xlslus.push(responseList);},"GeocodedAddress":function(node,responseList){var feature=new OpenLayers.Feature.Vector();this.readChildNodes(node,feature);responseList.features.push(feature);},"GeocodeMatchCode":function(node,feature){var matchCode={};matchCode.accuracy=node.getAttribute("accuracy");matchCode.matchType=node.getAttribute("matchType");feature.attributes.geocodeMatchCode=matchCode;},"ReverseGeocodeResponse":function(node,xlslus){this.readChildNodes(node,xlslus);},"ReverseGeocodedLocation":function(node,xlslus){var feature=new OpenLayers.Feature.Vector();this.readChildNodes(node,feature);xlslus.push(feature);},"SearchCentreDistance":function(node,feature){var distance={};distance.value=node.getAttribute("value");distance.accuracy=node.getAttribute("accuracy");distance.uom=node.getAttribute("uom");if(!distance.uom){distance.uom="M";}
feature.attributes.searchCentreDistance=distance;},"Address":function(node,feature){var countryCode=node.getAttribute("countryCode");var address=new this.addressClass(countryCode);address.addressee=node.getAttribute("addressee");this.readChildNodes(node,address);feature.attributes.address=address;},"freeFormAddress":function(node,address){address.freeFormAddress=this.getChildValue(node);},"StreetAddress":function(node,address){this.readChildNodes(node,address);},"Building":function(node,address){var building={};building.number=node.getAttribute("number");building.subdivision=node.getAttribute("subdivision");building.buildingName=node.getAttribute("buildingName");address.building=building;},"Street":function(node,address){var street={};street.name=this.getChildValue(node);street.directionalPrefix=node.getAttribute("directionalPrefix");street.typePrefix=node.getAttribute("typePrefix");street.officialName=node.getAttribute("officialName");street.typeSuffix=node.getAttribute("typeSuffix");street.directionalSuffix=node.getAttribute("directionalSuffix");street.muniOctant=node.getAttribute("muniOctant");if(!street.directionalPrefix&&!street.typePrefix&&!street.officialName&&!street.typeSuffix&&!street.directionalSuffix&&!street.muniOctant){street=street.name;}
address.street.push(street);},"Place":function(node,address){var type=node.getAttribute("type");address.place[type]=this.getChildValue(node);},"PostalCode":function(node,address){address.postalCode=this.getChildValue(node);}},"gml":{"Point":function(node,feature){var parser=this.parseGeometry["point"];var geometry=parser.apply(this,[node]);if(this.internalProjection&&this.externalProjection){geometry.transform(this.externalProjection,this.internalProjection);}
feature.geometry=geometry;}}},writeGeocodeRequest:function(address){return this.writers.xls.GeocodeRequest.apply(this,[address]);},writeReverseGeocodeRequest:function(position){return this.writers.xls.ReverseGeocodeRequest.apply(this,[position]);},writers:{"xls":{"GeocodeRequest":function(address){var root=this.createElementNSPlus("GeocodeRequest",{attributes:{"xsi:schemaLocation":this.schemaLocation}});if(!(address instanceof Array)){address=[address];}
for(var i=0;i<address.length;i++){this.writeNode(root,"Address",address[i]);}
return root;},"ReverseGeocodeRequest":function(position){var root=this.createElementNSPlus("ReverseGeocodeRequest",{attributes:{"xsi:schemaLocation":this.schemaLocation}});this.writeNode(root,"Position",position);return root;},"Address":function(address){var node=this.createElementNSPlus("Address",{attributes:{"countryCode":address.countryCode,"addressee":address.addressee}});if(address.freeFormAddress){this.writeNode(node,"freeFormAddess",address.freeFormAddress);}else{this.writeNode(node,"StreetAddress",address);if(address.place){var classification=Geozet.Format.XLSLUS.v1.NamedPlaceClassification;for(var i=0;i<classification.length;i++){if(address.place[classification[i]]){var placeNode=this.writeNode(node,"Place",address.place[classification[i]]);this.setAttributes(placeNode,{"type":classification[i]});}}}
if(address.postalCode){this.writeNode(node,"PostalCode",address.postalCode);}}
return node;},"freeFormAddress":function(freeFormAddress){return this.createElementNSPlus("freeFormAddress",{value:freeFormAddress});},"StreetAddress":function(address){var node=this.createElementNSPlus("StreetAddress",{});if(address.building){this.writeNode(node,"Building",address.building);}
var street=address.street;if(!(street instanceof Array)){street=[street];}
for(var i=0;i<street.length;i++){this.writeNode(node,"Street",street[i]);}
return node;},"Building":function(building){return this.createElementNSPlus("Building",{attributes:{"number":building.number,"subdivision":building.subdivision,"buildingName":building.buildingName}});},"Street":function(street){if(typeof street=='string'){return this.createElementNSPlus("Street",{value:street});}else if(street&&street.name){return this.createElementNSPlus("Street",{value:street.name});}else{return this.createElementNSPlus("Street",{attributes:{"directionalPrefix":street.directionalPrefix,"typePrefix":street.typePrefix,"officialName":street.officialName,"typeSuffix":street.typeSuffix,"directionalSuffix":street.directionalSuffix,"muniOctant":street.muniOctant}});}},"Place":function(place){return this.createElementNSPlus("Place",{value:place});},"PostalCode":function(postalCode){return this.createElementNSPlus("PostalCode",{value:postalCode});},"Position":function(position){var node=this.createElementNSPlus("Position",{attributes:{"levelOfConf":position.levelOfConf}});if(position.CLASS_NAME&&position.CLASS_NAME=="OpenLayers.Geometry.Point"){position={point:position};}
this.writeNode(node,"gml:Point",position.point);if(position.shape){if(position.shape.CLASS_NAME&&position.shape.CLASS_NAME=="OpenLayers.Geometry.Polygon"){this.writeNode(node,"gml:Polygon",position.shape);}else if(position.shape.CLASS_NAME&&position.shape.CLASS_NAME=="OpenLayers.Geometry.MultiPolygon"){this.writeNode(node,"gml:MultiPolygon",position.shape);}}
if(position.qop){}
if(position.time){}
if(position.speed){}
if(position.direction){}
return node;}},"gml":{"Point":function(point){var node=this.createElementNSPlus("gml:Point",{attributes:{srsName:this.srsName}});this.writeNode(node,"gml:pos",point);return node;},"pos":function(point){return this.createElementNSPlus("gml:pos",{value:point.x+' '+point.y});},"CircleByCenterPoint":function(geometry){},"Polygon":function(geometry){return this.buildGeometryNode(geometry);},"MultiPolygon":function(geometry){return this.buildGeometryNode(geometry);}}},getNamespacePrefix:function(uri){var prefix=null;if(uri==null){prefix=this.namespaces[this.defaultPrefix];}else{var gotPrefix=false;for(prefix in this.namespaces){if(this.namespaces[prefix]==uri){gotPrefix=true;break;}}
if(!gotPrefix){prefix=null;}}
return prefix;},readChildNodes:function(node,obj){var children=node.childNodes;var child,group,reader,prefix,local;for(var i=0;i<children.length;++i){child=children[i];if(child.nodeType==1){prefix=this.getNamespacePrefix(child.namespaceURI);local=child.nodeName.split(":").pop();group=this.readers[prefix];if(group){reader=group[local];if(reader){reader.apply(this,[child,obj]);}}}}},writeNode:function(parent,name,obj){var prefix,local;var split=name.indexOf(":");if(split>0){prefix=name.substring(0,split);local=name.substring(split+1);}else{prefix=this.getNamespacePrefix(parent.namespaceURI);local=name;}
var child=this.writers[prefix][local].apply(this,[obj]);parent.appendChild(child);return child;},createElementNSPlus:function(name,options){options=options||{};var loc=name.indexOf(":");var uri=options.uri||this.namespaces[options.prefix];if(!uri){loc=name.indexOf(":");uri=this.namespaces[name.substring(0,loc)];}
if(!uri){uri=this.namespaces[this.defaultPrefix];}
var node=this.createElementNS(uri,name);if(options.attributes){this.setAttributes(node,options.attributes);}
if(options.value){node.appendChild(this.createTextNode(options.value));}
return node;},setAttributes:function(node,obj){var value,loc,alias,uri;for(var name in obj){if(obj[name]){value=obj[name].toString();uri=this.namespaces[name.substring(0,name.indexOf(":"))]||null;this.setAttributeNS(node,uri,name,value);}}},CLASS_NAME:"Geozet.Format.XLSLUS.v1"});Geozet.Format.XLSLUS.v1.NamedPlaceClassification=["CountrySubdivision","CountrySecondarySubdivision","Municipality","MunicipalitySubdivision"];Geozet.Format.XLSLUS.v1_1_0=OpenLayers.Class(Geozet.Format.XLSLUS.v1,{VERSION:"1.1.0",schemaLocation:"http://www.opengis.net/xls http://schemas.opengis.net/ols/1.1.0/LocationUtilityService.xsd",initialize:function(options){Geozet.Format.XLSLUS.v1.prototype.initialize.apply(this,[options]);},CLASS_NAME:"Geozet.Format.XLSLUS.v1_1_0"});