/**
 * This is a configuration javascript file to create a layers list for pdok api
 *
 * At this moment it can contain 2 layertypes: WMTS (preferred) and WMS
 *
 * A layer Object is an Object with properties with OpenLayers-Layer property names
 * Only 'layertype' and 'name' are unique for the api
 *
 * NOTE: because we use OpenLayers properties, the property names are type aware:
 * eg: for a WMTS the layernames is defined in a 'layer' property
 * while for a WMS it is called 'layers' (mind the s on the end)
 */


Pdok.Api.prototype.defaultLayers = {

  AAN: {
    layertype: 'WMTS',
    name: 'AAN - Agrarisch Areaal Nederland (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts/',
    layer: 'aan',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  AHN1_100M: {
    layertype: 'WMTS',
    name: 'AHN1 - Actueel Hoogtebestand NL 100 meter (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'ahn1_100m',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  AHN1_5M: {
    layertype: 'WMTS',
    name: 'AHN1 - Actueel Hoogtebestand NL 5 meter (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'ahn1_5m',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  AHN1_BlADINDEX: {
    layertype: 'WMS',
    name: 'AHN1 - Actueel Hoogtebestand NL 25 meter - Bladindex (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/ahn1/wms',
    layers: 'ahn1_bladindex',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  AHN1_PUNTDICHTHEIDGEBIEDEN: {
    layertype: 'WMS',
    name: 'AHN1 - Actueel Hoogtebestand NL 25 meter - Pundichtheidgebieden (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/ahn1/wms',
    layers: 'puntdichtheidgebieden',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  AHN1_STADSPOLYGONEN: {
    layertype: 'WMS',
    name: 'AHN1 - Actueel Hoogtebestand NL 25 meter - Stadspolygonen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/ahn1/wms',
    layers: 'stadspolygonen',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  AHN1_VLIEGLIJNEN: {
    layertype: 'WMS',
    name: 'AHN1 - Actueel Hoogtebestand NL 25 meter - Vlieglijnen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/ahn1/wms',
    layers: 'vlieglijnen',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  AHN2_5M: {
    layertype: 'WMTS',
    name: 'AHN2 - Actueel Hoogtebestand NL 5 meter (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'ahn2_5m',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  AHN2_05M_INT: {
    layertype: 'WMTS',
    name: 'AHN2 - Actueel Hoogtebestand NL 0.5 meter geinterpoleerd (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'ahn2_05m_int',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  AHN2_05M_NON: {
    layertype: 'WMTS',
    name: 'AHN2 - Actueel Hoogtebestand NL 0.5 meter niet geinterpoleerd (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'ahn2_05m_non',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  AHN2_05M_RUW: {
    layertype: 'WMTS',
    name: 'AHN2 - Actueel Hoogtebestand NL 0.5 meter ruw (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'ahn2_05m_ruw',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  AHN3_5M_DSM: {
    layertype: 'WMTS',
    name: 'AHN3 - Actueel Hoogtebestand NL 5 meter DSM (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'ahn3_5m_dsm',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  AHN3_5M_DTM: {
    layertype: 'WMTS',
    name: 'AHN3 - Actueel Hoogtebestand NL 5 meter DTM (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'ahn3_5m_dtm',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  AHN3_0_5M_DSM: {
    layertype: 'WMTS',
    name: 'AHN3 - Actueel Hoogtebestand NL 0,5 meter DSM (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'ahn3_05m_dsm',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  AHN3_0_5M_DTM: {
    layertype: 'WMTS',
    name: 'AHN3 - Actueel Hoogtebestand NL 0,5 meter DTM (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'ahn3_05m_dtm',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  BAG: {
    layertype: 'WMTS',
    name: 'BAG - Basisadministratie Adressen en Gebouwen (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'bag',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  BAG_LIGPLAATS: {
    layertype: 'WMS',
    name: 'BAG - Ligplaats (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bag/wms/v1_1',
    layers: 'ligplaats',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  BAG_PAND: {
    layertype: 'WMS',
    name: 'BAG - Pand (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bag/wms/v1_1',
    layers: 'pand',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  BAG_STANDPLAATS: {
    layertype: 'WMS',
    name: 'BAG - Standplaats (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bag/wms/v1_1',
    layers: 'standplaats',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  BAG_VERBLIJFSOBJECT: {
    layertype: 'WMS',
    name: 'BAG - Verblijfsobject (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bag/wms/v1_1',
    layers: 'verblijfsobject',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  BAG_WOONPLAATS: {
    layertype: 'WMS',
    name: 'BAG - Woonplaats (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bag/wms/v1_1',
    layers: 'woonplaats',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  BBG2008: {
    layertype: 'WMS',
    name: 'BBG - Bestand Bodemgebruik 2008 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bestandbodemgebruik2008/wms',
    layers: 'bbg2008',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  BBG2008_hoofdgroep: {
    layertype: 'WMS',
    name: 'BBG - Bestand Bodemgebruik 2008 Hoofdgroep (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bestandbodemgebruik2008/wms',
    layers: 'bbg2008_hoofdgroep',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  BBG2010: {
    layertype: 'WMS',
    name: 'BBG - Bestand Bodemgebruik 2010 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bestandbodemgebruik2010/wms',
    layers: 'bbg2010',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  BBG2010_hoofdgroep: {
    layertype: 'WMS',
    name: 'BBG - Bestand Bodemgebruik 2010 Hoofdgroep (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bestandbodemgebruik2010/wms',
    layers: 'bbg2010_hoofdgroep',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  BESCHERMDENATUURMONUMENTEN: {
    layertype: 'WMS',
    name: 'Beschermde Natuurmonumenten (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/beschermdenatuurmonumenten/wms',
    layers: 'beschermdenatuurmonumenten',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  BG_PROVINCIEGRENZEN: {
    layertype: 'WMS',
    name: 'Bestuurlijke grenzen - Provinciegrenzen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/wms',
    layers: 'provincies',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  BG_GEMEENTEGRENZEN: {
    layertype: 'WMS',
    name: 'Bestuurlijke grenzen - Gemeentegrenzen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/wms',
    layers: 'gemeenten',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  BG_GEMEENTEGRENZEN_LABEL: {
    layertype: 'WMS',
    name: 'Bestuurlijke grenzen - Gemeentegrenzen met labels (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/wms?sld=' + Pdok.ApiUrl + '/sld/gemeentegrenzen_label_grijs_gestippeld.sld',
    layers: 'gemeenten',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  BG_LANDSGRENS: {
    layertype: 'WMS',
    name: 'Bestuurlijke grenzen - Landsgrens (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/wms',
    layers: 'landsgrens',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  BGT_ACHTERGROND_WMTS: {
    layertype: 'WMTS',
    name: 'Basisregistratie Grootschalige Topografie Achtergrond (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'bgtachtergrond',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  BGT_LIJNGERICHT_WMTS: {
    layertype: 'WMTS',
    name: 'Basisregistratie Grootschalige Topografie Lijngericht (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'bgtlijngericht',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  BGT_OMTREKGERICHT_WMTS: {
    layertype: 'WMTS',
    name: 'Basisregistratie Grootschalige Topografie Omtrekgericht (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'bgtomtrekgericht',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  BGT_STANDAARD_WMTS: {
    layertype: 'WMTS',
    name: 'Basisregistratie Grootschalige Topografie Standaard (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts',
    layer: 'bgtstandaard',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  BGT_PASTEL_WMTS: {
    layertype: 'WMTS',
    name: 'Basisregistratie Grootschalige Topografie Pastel (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'bgtpastel',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  BRP_LIGHT: {
    layertype: 'WMS',
    name: 'BRP-light - Gewaspercelen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/brpgewaspercelen/wms?',
    layers: 'brpgewaspercelen',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_KERNEN_NAMEN: {
    layertype: 'WMS',
    name: 'CBS Bevolkingskern namen 2008 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bevolkingskernen2008/wms',
    layers: 'naamgeving_kernen_40k_plus,naamgeving_kernen_alles',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_KERNEN: {
    layertype: 'WMS',
    name: 'CBS Bevolkingskernen 2008 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bevolkingskernen2008/wms',
    layers: 'cbsbevolkingskernen2008',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_KERNEN2011: {
    layertype: 'WMS',
    name: 'CBS Bevolkingskernen 2011 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bevolkingskernen2011/wms',
    layers: 'cbsbevolkingskernen2011',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_GEMEENTEN: {
    layertype: 'WMS',
    name: 'CBS Gemeentegrenzen 2008 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/bevolkingskernen2008/wms',
    layers: 'gemeentegrens_generalisatie_2008',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_VIERKANTEN100M_INWONERS2014: {
    layertype: 'WMS',
    name: 'CBS Vierkanten 100m - Inwoners 2014 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/cbsvierkanten100mv2/wms',
    layers: 'vierkant100m2014',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_VIERKANTENKANTEN100M_INWONERS2013: {
    layertype: 'WMS',
    name: 'CBS Vierkanten 100m - Inwoners 2013 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/cbsvierkanten100mv2/wms',
    layers: 'vierkant100m2013',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_VIERKANTEN100M_INWONERS2012: {
    layertype: 'WMS',
    name: 'CBS Vierkanten 100m - Inwoners 2012 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/cbsvierkanten100mv2/wms',
    layers: 'vierkant100m2012',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_VIERKANTEN100M_INWONERS2011: {
    layertype: 'WMS',
    name: 'CBS Vierkanten 100m - Inwoners 2011 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/cbsvierkanten100mv2/wms',
    layers: 'vierkant100m2011',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_4KANTEN500M_INWONERS2014: {
    layertype: 'WMS',
    name: 'CBS Vierkanten 500m - Inwoners 2014 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/cbsvierkanten500mv2/wms',
    layers: 'vierkant500m2014',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_4KANTEN500M_INWONERS2013: {
    layertype: 'WMS',
    name: 'CBS Vierkanten 500m - Inwoners 2013 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/cbsvierkanten500mv2/wms',
    layers: 'vierkant500m2013',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_4KANTEN500M_INWONERS2012: {
    layertype: 'WMS',
    name: 'CBS Vierkanten 500m - Inwoners 2012 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/cbsvierkanten500mv2/wms',
    layers: 'vierkant500m2012',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_4KANTEN500M_INWONERS2011: {
    layertype: 'WMS',
    name: 'CBS Vierkanten 500m - Inwoners 2011 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/cbsvierkanten500mv2/wms',
    layers: 'vierkant500m2011',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CULTUURHISTORISCHEOBJECTEN_ELEMENTEN: {
    layertype: 'WMS',
    name: 'Cultuurhistorische objecten - Elementen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/cultgis/wms',
    layers: 'elementen',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CULTUURHISTORISCHEOBJECTEN_AANDACHTSGEBIEDEN: {
    layertype: 'WMS',
    name: 'Cultuurhistorische objecten - Aandachtsgebieden (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/cultgis/wms',
    layers: 'aandachtsgebied',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CULTUURHISTORISCHEOBJECTEN_DEELLANDSCHAPPEN: {
    layertype: 'WMS',
    name: 'Cultuurhistorische objecten - Deellandschappen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/cultgis/wms',
    layers: 'deellandschap',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CULTUURHISTORISCHEOBJECTEN_LANDSCHAPPEN: {
    layertype: 'WMS',
    name: 'Cultuurhistorische objecten - Landschappen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/cultgis/wms',
    layers: 'landschap',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CULTUURHISTORISCHEOBJECTEN_REGIOS: {
    layertype: 'WMS',
    name: 'Cultuurhistorische objecten - Regio\'s (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/cultgis/wms',
    layers: 'regios',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  DTB_PUNTEN: {
    layertype: 'WMS',
    name: 'Digitaal Topografisch Bestand (DTB) - Punten (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/digitaaltopografischbestand/wms',
    layers: 'punten',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  DTB_LIJNEN: {
    layertype: 'WMS',
    name: 'Digitaal Topografisch Bestand (DTB) - Lijnen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/digitaaltopografischbestand/wms',
    layers: 'lijnen',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  DTB_VLAKKEN: {
    layertype: 'WMS',
    name: 'Digitaal Topografisch Bestand (DTB) - Vlakken (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/digitaaltopografischbestand/wms',
    layers: 'vlakken',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  ECOTOPEN_CYCLUS_01: {
    layertype: 'WMS',
    name: 'Ecotopen Cyclus 1 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/ecotopen/wms',
    layers: 'cyclus_een',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  ECOTOPEN_CYCLUS_02: {
    layertype: 'WMS',
    name: 'Ecotopen Cyclus 2 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/ecotopen/wms',
    layers: 'cyclus_twee',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  ECOTOPEN_CYCLUS_03: {
    layertype: 'WMS',
    name: 'Ecotopen Cyclus 3 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/ecotopen/wms',
    layers: 'cyclus_drie',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  FYSISCH_GEOGRAFISCHE_REGIOS: {
    layertype: 'WMS',
    name: 'Fysisch Geografische Regios (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/fysischgeografischeregios/wms',
    layers: 'fysischgeografischeregios',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  GELUIDSKAARTEN_ETMAAL: {
    layertype: 'WMS',
    name: 'Geluidskaarten etmaal (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/rwsgeluidskaarten/wms',
    layers: 'geluidskaartenetmaal',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  GELUIDSKAARTEN_NACHT: {
    layertype: 'WMS',
    name: 'Geluidskaarten nacht (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/rwsgeluidskaarten/wms',
    layers: 'geluidskaartennacht',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  GELUIDSKAARTEN_ETMAAL_2006: {
    layertype: 'WMS',
    name: 'Geluidskaarten etmaal 2006 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/rwsgeluidskaarten/wms',
    layers: 'geluidskaartenetmaal2006',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  GELUIDSKAARTEN_NACHT_2006: {
    layertype: 'WMS',
    name: 'Geluidskaarten nacht 2006 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/rwsgeluidskaarten/wms',
    layers: 'geluidskaartennacht2006',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  INSPIRE_ADRESSEN: {
    layertype: 'WMS',
    name: 'Adressen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/inspireadressen/wms',
    layers: 'inspireadressen',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  KNOOPPUNTEN: {
    layertype: 'WMS',
    name: 'Fietsknooppuntnetwerken (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/fietsknooppuntennetwerk/wms',
    layers: 'netwerken,knooppunten',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  LAWROUTES: {
    layertype: 'WMS',
    name: 'Lange-afstandswandelroutes (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/lawroutes/wms',
    layers: 'lawroutes',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  LFROUTES: {
    layertype: 'WMS',
    name: 'Landelijke Fietsroutes (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/lfroutes/wms',
    layers: 'lfroutes',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  PDOK_luchtfoto : {
    layertype: 'WMTS',
    name: 'PDOK achtergrond luchtfoto\'s (WMTS)',
    url: 'https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0?',
    version: "1.3.0",
    layer: 'Actueel_ortho25',
    style: '',
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: true,
    format: 'image/jpeg',
    attribution: '<a href="https://www.pdok.nl/introductie/-/article/luchtfoto-pdok" target="_blank">&copy; CC-BY-NC</a>',
    zoomOffset: 2
  },
  MOSSELENOESTERHABITATS: {
    layertype: 'WMS',
    name: 'Mossel en Oester habitats (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/mosselenoesterhabitats/wms',
    layers: 'mosselenoesterhabitats',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  MOSSELZAADINVANGINSTALLATIES: {
    layertype: 'WMS',
    name: 'Mosselzaad invanginstallaties (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/mosselzaadinvanginstallaties/wms',
    layers: 'mosselzaadinvanginstallaties',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NATIONALE_PARKEN: {
    layertype: 'WMS',
    name: 'Nationale parken (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nationaleparken/wms',
    layers: 'nationaleparken',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NATURA2000: {
    layertype: 'WMTS',
    name: 'Natura 2000 (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'natura2000',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  NATURA2000_WMS: {
    layertype: 'WMS',
    name: 'Natura 2000 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/natura2000/wms?',
    layers: 'natura2000',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NHI_DM_Links: {
    layertype: 'WMS',
    name: 'Nationaal Hydrologisch Instrumentarium (NHI) - DM Links (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nhi/wms',
    layers: 'dmlinks',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NHI_DM_NODES: {
    layertype: 'WMS',
    name: 'Nationaal Hydrologisch Instrumentarium (NHI) - DM Nodes (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nhi/wms',
    layers: 'dmnodes',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOK2011: {
    layertype: 'WMTS',
    name: 'NOK2011 - Natuurmeting Op Kaart (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'nok2011',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false
  },
  NOK2011_BEGRENZING_WMS: {
    layertype: 'WMS',
    name: 'NOK2011 - Begrenzing 2011 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nok2011/wms?',
    layers: 'begrenzing',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOK2011_EHS_WMS: {
    layertype: 'WMS',
    name: 'NOK2011 - EHS 2011 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nok2011/wms?',
    layers: 'planologischeehs',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOK2011_VERWERVINGINRICHTING_WMS: {
    layertype: 'WMS',
    name: 'NOK2011 - Verwerving inrichting 2011 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nok2011/wms?',
    layers: 'verwervinginrichting',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOK2012_BEGRENZING_WMS: {
    layertype: 'WMS',
    name: 'NOK2012 - Begrenzing 2012 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nok2012/wms?',
    layers: 'begrenzing',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOK2012_EHS_WMS: {
    layertype: 'WMS',
    name: 'NOK2012 - EHS 2012 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nok2012/wms?',
    layers: 'planologischeehs',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOK2012_VERWERVINGINRICHTING_WMS: {
    layertype: 'WMS',
    name: 'NOK2012 - Verwerving inrichting 2012 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nok2012/wms?',
    layers: 'verwervinginrichting',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOK2012_BEHEER_WMS: {
    layertype: 'WMS',
    name: 'NOK2012 - Beheer 2012 (WMS)',
    url: 'https://test.geodata.nationaalgeoregister.nl/nok2012/wms?',
    layers: 'beheer',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOK2013_BEGRENZING_WMS: {
    layertype: 'WMS',
    name: 'NOK2013 - Begrenzing 2013 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nok2013/wms?',
    layers: 'begrenzing',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOK2013_EHS_WMS: {
    layertype: 'WMS',
    name: 'NOK2013 - EHS 2013 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nok2013/wms?',
    layers: 'planologischeehs',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOK2013_VERWERVINGINRICHTING_WMS: {
    layertype: 'WMS',
    name: 'NOK2013 - Verwerving inrichting 2013 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nok2013/wms?',
    layers: 'verwervinginrichting',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOK2013_BEHEER_WMS: {
    layertype: 'WMS',
    name: 'NOK2013 - Beheer 2013 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nok2013/wms?',
    layers: 'beheer',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOK2014_BEGRENZING_WMS: {
    layertype: 'WMS',
    name: 'NOK2014 - Begrenzing 2014 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nok2014/wms?',
    layers: 'begrenzing',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOK2014_EHS_WMS: {
    layertype: 'WMS',
    name: 'NOK2014 - EHS 2014 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nok2014/wms?',
    layers: 'planologischeehs',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOK2014_VERWERVINGINRICHTING_WMS: {
    layertype: 'WMS',
    name: 'NOK2014 - Verwerving inrichting 2014 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nok2014/wms?',
    layers: 'verwervinginrichting',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOK2014_BEHEER_WMS: {
    layertype: 'WMS',
    name: 'NOK2014 - Beheer 2014 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nok2014/wms?',
    layers: 'beheer',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOORD_KABELS_WMS: {
    layertype: 'WMS',
    name: 'Noordzee Kabels (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/noordzeekabelsenleidingen/wms?',
    layers: 'kabels',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOORD_LEID_WMS: {
    layertype: 'WMS',
    name: 'Noordzee Leidingen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/noordzeekabelsenleidingen/wms?',
    layers: 'leidingen',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOORD_WIN_WMS: {
    layertype: 'WMS',
    name: 'Noordzee Wingebieden (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/noordzeewingebieden/wms?',
    layers: 'noordzeewingebieden',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOORD_VAARDRIJVEND_WMS: {
    layertype: 'WMS',
    name: 'Noordzee Vaarwegmarkeringen Drijvend (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/noordzeevaarwegmarkeringenrd/wms?',
    layers: 'markdrijvendrd',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NOORD_VAARVAST_WMS: {
    layertype: 'WMS',
    name: 'Noordzee Vaarwegmarkeringen Vast (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/noordzeevaarwegmarkeringenrd/wms?',
    layers: 'markvastrd',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NWB_SPOORWEGEN: {
    layertype: 'WMS',
    name: 'NWB Spoorwegen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nwbspoorwegen/wms',
    layers: 'hectopunten,overgangen,oversteken,spoorvakken,treinstations',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NWB_VAARWEGEN: {
    layertype: 'WMS',
    name: 'NWB Vaarwegen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nwbvaarwegen/wms',
    layers: 'vaarwegvakken,kmmarkeringen',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  NWB_WEGEN: {
    layertype: 'WMS',
    name: 'NWB Wegen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/nwbwegen/wms',
    layers: 'wegvakken,hectopunten',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  OpenTopo_Achtergrondkaart: {
    layertype: 'WMTS',
    name: 'Open Topo Achtergrondkaart',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'opentopoachtergrondkaart',
    transparent: 'true',
    format: 'image/png',
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: true,
    singleTile: true
  },
  OpenTopo: {
    layertype: 'WMTS',
    name: 'Open Topo',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'opentopo',
    transparent: 'true',
    format: 'image/png',
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  OVERHEIDSDIENSTEN: {
    layertype: 'WMS',
    name: 'Administratieve en sociale overheidsdiensten (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/overheidsdiensten/wms',
    layers: 'overheidsdiensten',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  PUBLIEKRECHTELIJKEBEPERKING: {
    layertype: 'WMS',
    name: 'Publiekrechtelijke Beperkingen (WMS)',
    url: ' https://service.pdok.nl/kadaster/wkpb/wms/v1_0?',
    layers: 'wetbodembescherming',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  RD_INFO_STATIONS: {
    layertype: 'WMS',
    name: 'RD Info Stations (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/rdinfo/wms',
    layers: 'stations',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  RD_INFO_PUNTEN: {
    layertype: 'WMS',
    name: 'RD Info Punten (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/rdinfo/wms',
    layers: 'punten',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  RWSOPPERVLAKTEWATERLICHAMEN_VLAKKEN: {
    layertype: 'WMS',
    name: 'RWS Oppervlaktewaterlichamen - vlakken (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/rwsoppervlaktewaterlichamen/wms',
    layers: 'vlakken',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  RWSOPPERVLAKTEWATERLICHAMEN_LIJNEN: {
    layertype: 'WMS',
    name: 'RWS Oppervlaktewaterlichamen - lijnen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/rwsoppervlaktewaterlichamen/wms',
    layers: 'lijnen',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  SCHELPDIERENPERCELEN: {
    layertype: 'WMS',
    name: 'Schelpdieren Percelen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/schelpdierenpercelen/wms',
    layers: 'schelpdierenpercelen',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  SCHELPDIERWATER: {
    layertype: 'WMS',
    name: 'Schelpdierwater (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/schelpdierwater/wms',
    layers: 'schelpdierwater',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  Stedelijk_Water_Riolering_Beheergegevens_Put: {
    layertype: 'WMS',
    name: 'Beheergegevens Put',
    url: 'https://geodata.nationaalgeoregister.nl/rioned/gwsw/wms/v1_0?',
    layers: 'beheer_put',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  Stedelijk_Water_Riolering_Beheergegevens_Leiding: {
    layertype: 'WMS',
    name: 'Beheergegevens Leiding',
    url: 'https://geodata.nationaalgeoregister.nl/rioned/gwsw/wms/v1_0?',
    layers: 'beheer_leiding',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  Stedelijk_Water_Riolering_Beheer_Gebied: {
    layertype: 'WMS',
    name: 'Beheer gebied',
    url: 'https://geodata.nationaalgeoregister.nl/rioned/gwsw/wms/v1_0?',
    layers: 'beheer_leiding',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  Stedelijk_Water_Riolering_Beheer_Pomp: {
    layertype: 'WMS',
    name: 'Beheer pomp',
    url: 'https://geodata.nationaalgeoregister.nl/rioned/gwsw/wms/v1_0?',
    layers: 'beheer_pomp',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  Stedelijk_Water_Riolering_Beheer_Lozing: {
    layertype: 'WMS',
    name: 'Beheer lozing',
    url: 'https://geodata.nationaalgeoregister.nl/rioned/gwsw/wms/v1_0?',
    layers: 'beheer_lozing',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  Stedelijk_Water_Riolering_Beheer_Bouwwerk: {
    layertype: 'WMS',
    name: 'Beheer bouwwerk',
    url: 'https://geodata.nationaalgeoregister.nl/rioned/gwsw/wms/v1_0?',
    layers: 'beheer_bouwwerk',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  STREEKPADEN: {
    layertype: 'WMS',
    name: 'Nationale Streekpaden (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/streekpaden/wms',
    layers: 'streekpaden',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  SPOORWEGEN_TRACE: {
    layertype: 'WMS',
    name: 'Spoorwegen trace (spoorbaanhartlijn) (WMS)',
    url: ' https://service.pdok.nl/prorail/spoorwegen/wms/v1_0?',
    layers: 'trace',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  SPOORWEGEN_KILOMETRERING: {
    layertype: 'WMS',
    name: 'Spoorwegen kilometrering (spoorbaanhartpunt) (WMS)',
    url: ' https://service.pdok.nl/prorail/spoorwegen/wms/v1_0?',
    layers: 'kilometrering',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  SPOORWEGEN_SPOORAS: {
    layertype: 'WMS',
    name: 'Spoorwegen spooras (WMS)',
    url: ' https://service.pdok.nl/prorail/spoorwegen/wms/v1_0?',
    layers: 'spooras',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  SPOORWEGEN_WISSEL: {
    layertype: 'WMS',
    name: 'Spoorwegen wissel (WMS)',
    url: ' https://service.pdok.nl/prorail/spoorwegen/wms/v1_0?',
    layers: 'wissel',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  SPOORWEGEN_KRUISING: {
    layertype: 'WMS',
    name: 'Spoorwegen kruising (WMS)',
    url: ' https://service.pdok.nl/prorail/spoorwegen/wms/v1_0?',
    layers: 'kruising',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  SPOORWEGEN_STATION: {
    layertype: 'WMS',
    name: 'Spoorwegen station (WMS)',
    url: ' https://service.pdok.nl/prorail/spoorwegen/wms/v1_0?',
    layers: 'station',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  SPOORWEGEN_OVERWEG: {
    layertype: 'WMS',
    name: 'Spoorwegen overweg (WMS)',
    url: ' https://service.pdok.nl/prorail/spoorwegen/wms/v1_0?',
    layers: 'overweg',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  STORTENLOSWALLEN_VAK: {
    layertype: 'WMS',
    name: 'Sort en Loswallen - vakindeling (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/stortenloswallen/wms',
    layers: 'stortenloswalvakindeling',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  STORTENLOSWALLEN: {
    layertype: 'WMS',
    name: 'Sort en Loswallen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/stortenloswallen/wms',
    layers: 'stortloswal',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  TOP10NL: {
    layertype: 'WMTS',
    name: 'TOP10 NL (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'top10nlv2',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false,
    attribution: '(c) Kadaster'
  },
  TOP250RASTER: {
    layertype: 'WMTS',
    name: 'TOP250NL Raster (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'top250raster',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false,
    attribution: '(c) Kadaster'
  },
  TOP25RASTER: {
    layertype: 'WMTS',
    name: 'TOP25NL Raster (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'top25raster',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false,
    attribution: '(c) Kadaster'
  },
  TOP50RASTER: {
    layertype: 'WMTS',
    name: 'TOP50NL Raster (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'top50raster',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false,
    attribution: '(c) Kadaster'
  },
  TOP50VECTOR: {
    layertype: 'WMTS',
    name: 'TOP50NL Vector (WMTS)',
    url: 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?',
    layer: 'top50raster',
    style: null,
    matrixSet: 'EPSG:28992',
    visibility: true,
    isBaseLayer: false,
    attribution: '(c) Kadaster'
  },
  VERKEERSSCHEIDINGSSTELSEL_ANKERGEBIEDEN: {
    layertype: 'WMS',
    name: 'Verkeersscheidingsstelsel - Ankergebieden (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/verkeersscheidingsstelsel/wms',
    layers: 'ankergebieden',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  VERKEERSSCHEIDINGSSTELSEL_BEGRENZING: {
    layertype: 'WMS',
    name: 'Verkeersscheidingsstelsel - Begrenzing (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/verkeersscheidingsstelsel/wms',
    layers: 'begrenzing',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  VERKEERSSCHEIDINGSSTELSEL_SEPERATIEZONES: {
    layertype: 'WMS',
    name: 'Verkeersscheidingsstelsel - Seperatiezones (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/verkeersscheidingsstelsel/wms',
    layers: 'seperatiezones',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  VERKEERSSCHEIDINGSSTELSEL_KILOMETRERINGLABELS: {
    layertype: 'WMS',
    name: 'Verkeersscheidingsstelsel - Kilometreringlabels (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/verkeersscheidingsstelsel/wms',
    layers: 'kilometreringlabels',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  VERKEERSSCHEIDINGSSTELSEL_VAARGEULENPERTYPEENTITEIT: {
    layertype: 'WMS',
    name: 'Verkeersscheidingsstelsel - Vaargeulen per type entiteit (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/verkeersscheidingsstelsel/wms',
    layers: 'vaargeulenpertypeentiteit',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  VIN_BEVAARBAARHEID: {
    layertype: 'WMS',
    name: 'Vaarkenmerken in Nederland (VIN) - Bevaarbaarheid (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/vin/wms',
    layers: 'bevaarbaarheid',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  WEGGEGEVENS_RIJBANEN: {
    layertype: 'WMS',
    name: 'Weggegevens - aantal rijbanen (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/weggeg/wms',
    layers: 'weggegaantalrijbanen',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  WEGGEGEVENS_MAXSNELHEID: {
    layertype: 'WMS',
    name: 'Weggegevens - maximum snelheid (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/weggeg/wms',
    layers: 'weggegmaximumsnelheden',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  WETLANDS: {
    layertype: 'WMS',
    name: 'Wetlands (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wetlands/wms?',
    layers: 'wetlands',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSBUURTEN2014: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Buurten 2014 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2014/wms?',
    layers: 'cbs_buurten_2014',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSWIJKEN2014: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Wijken 2014 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2014/wms?',
    layers: 'cbs_wijken_2014',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSGEMEENTEN2014: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Gemeenten 2014 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2014/wms?',
    layers: 'gemeenten2014',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSBUURTEN2013: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Buurten 2013 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2013/wms?',
    layers: 'cbs_buurten_2013',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSWIJKEN2013: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Wijken 2013 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2013/wms?',
    layers: 'cbs_wijken_2013',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSGEMEENTEN2013: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Gemeenten 2013 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2013/wms?',
    layers: 'gemeenten2013',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSBUURTEN2012: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Buurten 2012 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2012/wms?',
    layers: 'cbs_buurten_2012',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSWIJKEN2012: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Wijken 2012 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2012/wms?',
    layers: 'cbs_wijken_2012',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSGEMEENTEN2012: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Gemeenten 2012 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2012/wms?',
    layers: 'gemeenten2012',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSBUURTEN2011: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Buurten 2011 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2011/wms?',
    layers: 'cbs_buurten_2011',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSWIJKEN2011: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Wijken 2011 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2011/wms?',
    layers: 'cbs_wijken_2011',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSGEMEENTEN2011: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Gemeenten 2011 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2011/wms?',
    layers: 'gemeenten2011',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSBUURTEN2010: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Buurten 2010 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2010/wms?',
    layers: 'cbs_buurten_2010',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSWIJKEN2010: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Wijken 2010 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2010/wms?',
    layers: 'cbs_wijken_2010',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSGEMEENTEN2010: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Gemeenten 2010 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2010/wms?',
    layers: 'gemeenten2010',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSBUURTEN2009: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Buurten 2009 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2009/wms?',
    layers: 'cbs_buurten_2009',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSWIJKEN2009: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Wijken 2009 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2009/wms?',
    layers: 'cbs_wijken_2009',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  },
  CBS_WIJKENENBUURTEN_CBSGEMEENTEN2009: {
    layertype: 'WMS',
    name: 'CBS Wijken en buurten - Gemeenten 2009 (WMS)',
    url: 'https://geodata.nationaalgeoregister.nl/wijkenbuurten2009/wms?',
    layers: 'gemeenten2009',
    transparent: 'true',
    format: 'image/png',
    visibility: true,
    isBaseLayer: false,
    singleTile: true
  }
}
